export const ADD_TRIP = 'ADD_TRIP'
export const ADD_PAYMENT = 'ADD_PAYMENT'
export const UPDATE_NEW_PAYMENT = 'UPDATE_NEW_PAYMENT'
export const REMOVE_MEMBER_FROM_NEW_PAYMENT = 'REMOVE_MEMBER_FROM_NEW_PAYMENT'
