export const ADD_TRIP = 'ADD_TRIP'
export const ADD_PAYMENT = 'ADD_PAYMENT'
export const START_UPDATING_PAYMENT = 'START_UPDATING_PAYMENT'
export const SPENT_EQUALLY_SWITCHED = 'SPENT_EQUALLY_SWITCHED'
export const PAID_ONE_SWITCHED = 'PAID_ONE_SWITCHED'
export const REMOVE_MEMBER_FROM_PAYMENT = 'REMOVE_MEMBER_FROM_PAYMENT'
export const CHANGE_MEMBER_SPENT_ON_PAYMENT = 'CHANGE_MEMBER_SPENT_ON_PAYMENT'
export const UPDATE_PAYMENT = 'UPDATE_PAYMENT'
export const CANCEL_UPDATING_PAYMENT = 'CANCEL_UPDATING_PAYMENT'

export const TEMPORARY_ID = -1
